Metrics/AbcSize:
  Max: 29

Metrics/MethodLength:
  Max: 29

Style/GlobalVars:
  Exclude:
    - ext/tree_sitter/extconf.rb

# `unless` is cool and all, but I'd rather not. Less confusion.
Style/NegatedIf:
  Enabled: false
