build-dir = "vendor/parsers/build"
out-dir = "vendor/parsers"
tree-sitter-version = "0.24.5"

[parsers]
embedded-template = "0.23.2"
html = "0.23.2"
javascript = "0.23.1"
json = "0.24.8"
math = { ref = "ed50340a0c331b5b2559fa69d8c530b2aca4d309", from = "https://github.com/DerekStride/tree-sitter-math" }
ruby = "0.23.1"
