#include "tree_sitter.h"

VALUE mTreeSitter;

void Init_tree_sitter() {
  mTreeSitter = rb_define_module("TreeSitter");

  /**
   * The latest ABI version that is supported by the current version of the
   * library. When Languages are generated by the Tree-sitter CLI, they are
   * assigned an ABI version number that corresponds to the current CLI version.
   * The Tree-sitter library is generally backwards-compatible with languages
   * generated using older CLI versions, but is not forwards-compatible.
   */
  rb_define_const(mTreeSitter, "LANGUAGE_VERSION",
                  INT2NUM(TREE_SITTER_LANGUAGE_VERSION));

  /**
   * The earliest ABI version that is supported by the current version of the
   * library.
   */
  rb_define_const(mTreeSitter, "MIN_COMPATIBLE_LANGUAGE_VERSION",
                  TREE_SITTER_MIN_COMPATIBLE_LANGUAGE_VERSION);

  init_encoding();
  init_input();
  init_input_edit();
  init_language();
  init_logger();
  init_node();
  init_parser();
  init_point();
  init_quantifier();
  init_query();
  init_query_capture();
  init_query_cursor();
  init_query_error();
  init_query_match();
  init_query_predicate_step();
  init_range();
  init_symbol_type();
  init_tree();
  init_tree_cursor();
}
