#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'logger'
require 'optparse'
require 'tree_stand'
require 'tree_stand/cli'

$stdout.sync = $stderr.sync = true

program = TreeStand::Cli::Options.new
OptionParser.new do |parser|
  program.define_options(parser)
  parser.parse!(ARGV)
end
program.check!

def main(program)
  program.tree.query(program.query).each do |match|
    pp match.transform_values(&:text)
  end
end

main(program)
