# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module TreeSitter::Query::QueryPredicateStep::CAPTURE; end
module TreeSitter::Query::QueryPredicateStep::DONE; end
module TreeSitter::Query::QueryPredicateStep::STRING; end
