name: rubygems.org
on:
  release:
    types: [published]

jobs:
  publish_gem:
    name: Publish to Rubygems
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch Github Release Asset
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          file: tree_sitter.*.gem
          regex: true
          target: pkg/

      - name: Extract & Display structure of built gems
        run: ls -l pkg/

      - name: Release Gem
        uses: cadwallion/publish-rubygems-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
          RELEASE_COMMAND: bin/publish
